{
 "title": "Keycloak Status",
 "tags": [
  "payment-system",
  "keycloak"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Keycloak UP",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"keycloak\"}"
    }
   ]
  },
  {
   "title": "Keycloak scrape duration (s)",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 0, "w": 16, "h": 6 },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"keycloak\"}"
    }
   ]
  },
  {
   "title": "Keycloak samples scraped",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 6, "w": 24, "h": 7 },
   "targets": [
    {
     "expr": "scrape_samples_scraped{job=\"keycloak\"}"
    }
   ]
  }
 ]
}